// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("AlgebraProblemGenerator")>]
[<assembly: AssemblyProductAttribute("AlgebraProblemGenerator")>]
[<assembly: AssemblyDescriptionAttribute("Algebra problem generator from similar problems implementation as seen in Microsoft Research's: http://people.csail.mit.edu/rohitsingh/aaai12_rohit.pdf Written in F#")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "AlgebraProblemGenerator"
    let [<Literal>] AssemblyProduct = "AlgebraProblemGenerator"
    let [<Literal>] AssemblyDescription = "Algebra problem generator from similar problems implementation as seen in Microsoft Research's: http://people.csail.mit.edu/rohitsingh/aaai12_rohit.pdf Written in F#"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
